# Configuration for the Loggamera integration
# This allows for customizing service information

# Define services available from this integration
service:
  execute_scenario:
    name: Execute scenario
    description: Execute a scenario on your Loggamera devices
    fields:
      scenario_id:
        name: Scenario ID
        description: "ID of the scenario to execute"
        required: true
        selector:
          number:
            min: 1
            step: 1
            mode: box
      duration_minutes:
        name: Duration (minutes)
        description: "Duration in minutes for the scenario (if applicable)"
        required: false
        selector:
          number:
            min: 1
            step: 1
            mode: box
      entry_id:
        name: Integration Entry ID
        description: "Entry ID of the Loggamera integration (only needed if you have multiple instances)"
        required: false
        selector:
          text:
