# Service definitions for Loggamera integration

execute_scenario:
  name: Execute Scenario
  description: Execute a predefined scenario in Loggamera
  fields:
    scenario_id:
      name: Scenario ID
      description: ID of the scenario to execute
      required: true
      example: "12345"
      selector:
        text:

set_property:
  name: Set Property
  description: Set a property on a Loggamera device
  fields:
    device_id:
      name: Device ID
      description: ID of the device to set property on
      required: true
      example: "67890"
      selector:
        text:
    property_name:
      name: Property Name
      description: Name of the property to set
      required: true
      example: "targetTemperature"
      selector:
        text:
    property_value:
      name: Property Value
      description: Value to set the property to
      required: true
      example: "22.5"
      selector:
        text: