name: Validate Manifest

on:
  push:
  pull_request:

jobs:
  validate-manifest:
    runs-on: "ubuntu-latest"
    name: Validate manifest
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Setup Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema requests
      - name: Validate manifest.json
        run: |
          python -c "
          import json
          import jsonschema
          import requests

          # Load manifest
          with open('custom_components/loggamera/manifest.json') as f:
              manifest = json.load(f)

          # Basic validation
          required_fields = ['domain', 'name', 'documentation', 'issue_tracker', 'version']
          for field in required_fields:
              assert field in manifest, f'Missing required field: {field}'

          # Check URLs are accessible
          for url_field in ['documentation', 'issue_tracker']:
              if url_field in manifest:
                  url = manifest[url_field]
                  print(f'Checking {url_field}: {url}')
                  # Note: Only validate format, not actual accessibility in CI
                  assert url.startswith('https://'), f'{url_field} must be HTTPS'

          print('✅ Manifest validation passed')
          "